### ISSUE TITLE
Admin settings: Change base URL of the API

### ISSUE THREAD

**Issue by petenelson** [petenelson/wp-rest-api-toolbox#3]

**Comment by AymanEG** [comment]
Hello there ,

Your tool is awesome. I tried to take the class of this feature (renaming wp-json) and adding it to my custom plugin ,but it does not change anything

Can you list complete function with hooks to change it ?!

regards
Ayman

**Comment by petenelson** [comment]
You can use the `rest_url_prefix` hook to change the prefix.  https://developer.wordpress.org/reference/hooks/rest_url_prefix/
