### ISSUE TITLE
How do I restrict API access only to my own web api?

### ISSUE THREAD

**Issue by paviad** [petenelson/wp-rest-api-toolbox#41]
I have a website which includes 3 parts: A front-end application written in Angular, a Web API written in ASP.NET Core, and a Wordpress section.

I want to be able to use the Angular front-end UI to insert or delete posts in the Wordpress section, and I have an authentication scheme between my Angular app and my Web API.

So what I actually need is for my Web API to be able to use the Wordpress REST API, and to prevent anyone else from using it.

How would I achieve that?

**Comment by petenelson** [comment]
This would be outside the scope of what the REST API Toolbox could do, but I should still be able to offer some suggestions.

In this scenario, it might make sense to have the ASP.NET server-side code send the requests to the WordPress REST API vs the Angular JS making the request. Using a pre-shared key might be the way to do, and you could verify this in the `permission_callback` defined if you're creating a custom endpoint.  If you're using the core endpoints, you'd want to add a `determine_current_user` filter to check a pre-shared key or some other authentication method against a specific WP user, which will allow WP to run its standard `current_user_can()` checks.

I have some slides and sample code at https://petenelson.io/extending-the-wp-rest-api/ which might be of assistance, specifically slide 14 dealing with custom authentication.
